### ISSUE TITLE
Feature request: Dark theme (with a suggestion of what the CSS code could be)

### ISSUE THREAD

**Issue by hasB4K** [aesqe/firefox-downloads-sidebar#11]
Hi,

It would be awesome to add a Dark Theme (like Tree Style Tab). It could be a simple option.
So far I am overriding the css in the `chrome/userContent.css` in my Firefox's profile like this:

```css
@-moz-document url("moz-extension://[...extension-hash...]/sidebar/panel.html")
{
    html, body {
        background-color: #222 !important;
        color: #EEE !important;
    }

    .toolbar-item .btn,
    .change-state-button
    {
        filter: invert(90%) !important;
    }

    .progress
    {
        border: 1px solid #777 !important;
        background-color: #CCC !important;
    }

    .toolbar-bottom
    {
        border-top: 1px solid #777 !important;
    }

    .selected
    {
        background-image: linear-gradient(to top, #444, #444) !important;
        box-shadow: 0 0 1px 1px #777 !important;
    }
}
```

Thanks for the great add-on!
Best regards,
